source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'MMProgressSwift_Example' do
	pod 'MMProgressSwift', :path => '../'
	pod 'SpinKit'
    pod 'TOMSMorphingLabel'
end

target 'MMProgressSwift_Tests' do
	pod 'MMProgressSwift', :path => '../'
	pod 'SpinKit'
    pod 'TOMSMorphingLabel'
end